# Generated by Django 6.0.4 on 2026-04-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם בית הספר')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='כתובת')),
                ('days_per_week', models.PositiveSmallIntegerField(default=5, verbose_name='ימי לימוד בשבוע')),
                ('periods_per_day', models.PositiveSmallIntegerField(default=10, verbose_name='שיעורים ביום')),
                ('period_duration_minutes', models.PositiveSmallIntegerField(default=45, verbose_name='אורך שיעור (דקות)')),
                ('first_period_start', models.TimeField(default='08:00', verbose_name='שעת התחלה')),
            ],
            options={
                'verbose_name': 'בית ספר',
                'verbose_name_plural': 'בתי ספר',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='שם חדר')),
                ('capacity', models.PositiveSmallIntegerField(default=40, verbose_name='קיבולת')),
                ('room_type', models.CharField(blank=True, max_length=50, verbose_name='סוג חדר')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='school.school')),
            ],
            options={
                'verbose_name': 'חדר',
                'verbose_name_plural': 'חדרים',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='שכבה')),
                ('level', models.PositiveSmallIntegerField(verbose_name='מספר שכבה')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='סדר')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.school')),
            ],
            options={
                'verbose_name': 'שכבה',
                'verbose_name_plural': 'שכבות',
                'ordering': ['level'],
                'unique_together': {('school', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='מספר כיתה')),
                ('class_type', models.CharField(choices=[('regular', 'רגילה'), ('special_ed', 'חינוך מיוחד'), ('leadership', 'מנהיגות'), ('other', 'אחר')], default='regular', max_length=20, verbose_name='סוג כיתה')),
                ('student_count', models.PositiveSmallIntegerField(default=0, verbose_name='מספר תלמידים')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.grade')),
            ],
            options={
                'verbose_name': 'כיתה',
                'verbose_name_plural': 'כיתות',
                'ordering': ['grade__level', 'number'],
                'unique_together': {('grade', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'ראשון'), (2, 'שני'), (3, 'שלישי'), (4, 'רביעי'), (5, 'חמישי')], verbose_name='יום')),
                ('period', models.PositiveSmallIntegerField(verbose_name='שיעור')),
                ('start_time', models.TimeField(verbose_name='שעת התחלה')),
                ('end_time', models.TimeField(verbose_name='שעת סיום')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='school.school')),
            ],
            options={
                'verbose_name': 'משבצת זמן',
                'verbose_name_plural': 'משבצות זמן',
                'ordering': ['day', 'period'],
                'unique_together': {('school', 'day', 'period')},
            },
        ),
    ]
