# Generated by Django 6.0.4 on 2026-05-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('subjects', '0002_teacher_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='subjects.teacher', verbose_name='מחנכ/ת'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='track_label_raw',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='תווית מסלול גולמית'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_type',
            field=models.CharField(choices=[('regular', 'רגילה'), ('special_ed', 'חינוך מיוחד'), ('leadership', 'מנהיגות'), ('mofet_science', 'מופ"ת מדעית'), ('mofet_leadership', 'מופ"ת מנהיגות'), ('reserve_science', 'עתודה מדעית'), ('omets', 'אומ"ץ'), ('mabar', 'מב"ר'), ('talm', 'תל"מ'), ('atgar', 'אתגר'), ('biotech', 'ביוטכנולוגיה'), ('other', 'אחר')], default='regular', max_length=20, verbose_name='סוג כיתה'),
        ),
    ]
