# Generated by Django 6.0.4 on 2026-05-18
"""
Add UserProfile.teacher and UserProfile.school_class — the link the
mobile app needs to know which Teacher / SchoolClass the logged-in
user represents.

The RunPython data step auto-links existing teacher accounts by
case-insensitive email match. Admins / students stay unlinked and the
mobile app falls back to manual class selection in their settings.
"""
import django.db.models.deletion
from django.db import migrations, models


def link_existing_teachers(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    Teacher = apps.get_model('subjects', 'Teacher')
    linked = 0
    for p in UserProfile.objects.filter(teacher__isnull=True).select_related('user'):
        email = (p.user.email or '').strip()
        if not email:
            continue
        t = Teacher.objects.filter(email__iexact=email).first()
        if t:
            p.teacher = t
            p.save(update_fields=['teacher'])
            linked += 1
    if linked:
        print(f'    linked {linked} teacher account(s) by email match')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolclass_homeroom_teacher_and_more'),
        ('subjects', '0004_teachingassignment_additional_classes'),
        ('users', '0002_auth_overhaul'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='users_otpco_user_id_218e66_idx',
            old_name='users_otpcod_user_id_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_class',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_profiles',
                to='school.schoolclass',
                verbose_name='כיתה משויכת',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_profile',
                to='subjects.teacher',
                verbose_name='מורה משויך',
            ),
        ),
        migrations.RunPython(link_existing_teachers, noop),
    ]
