# Generated by Django 6.0.4 on 2026-05-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_teacher_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='dtmf_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='dtmf_verified',
            field=models.BooleanField(default=False),
        ),
    ]
