# Generated by Django 6.0.4 on 2026-04-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='שם קובץ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='הועלה ב')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('processing', 'מעבד'), ('completed', 'הושלם'), ('failed', 'נכשל')], default='pending', max_length=10, verbose_name='סטטוס')),
                ('subjects_imported', models.PositiveIntegerField(default=0, verbose_name='מקצועות שיובאו')),
                ('teachers_imported', models.PositiveIntegerField(default=0, verbose_name='מורים שיובאו')),
                ('assignments_imported', models.PositiveIntegerField(default=0, verbose_name='שיבוצים שיובאו')),
                ('errors', models.JSONField(default=list, verbose_name='שגיאות')),
                ('log', models.TextField(blank=True, verbose_name='לוג')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='school.school')),
            ],
            options={
                'verbose_name': 'לוג ייבוא',
                'verbose_name_plural': 'לוגי ייבוא',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
