# Generated by Django 6.0.4 on 2026-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='classes_imported',
            field=models.PositiveIntegerField(default=0, verbose_name='כיתות שיובאו'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='פירוט מלא'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='is_dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importlog',
            name='preview_data',
            field=models.JSONField(default=dict, verbose_name='תצוגה מקדימה'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='roles_imported',
            field=models.PositiveIntegerField(default=0, verbose_name='תפקידים שיובאו'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='warnings',
            field=models.JSONField(default=list, verbose_name='אזהרות'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('processing', 'מעבד'), ('preview', 'תצוגה מקדימה'), ('completed', 'הושלם'), ('failed', 'נכשל')], default='pending', max_length=10, verbose_name='סטטוס'),
        ),
    ]
