# Generated by Django 6.0.4 on 2026-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0002_importlog_classes_imported_importlog_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/', verbose_name='קובץ מקור'),
        ),
    ]
