# Generated by Django 6.0.4 on 2026-04-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_he', models.CharField(max_length=100, verbose_name='שם המקצוע')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Subject name')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='צבע')),
                ('requires_consecutive', models.BooleanField(default=False, verbose_name='דורש שיעורים צמודים')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school')),
            ],
            options={
                'verbose_name': 'מקצוע',
                'verbose_name_plural': 'מקצועות',
                'ordering': ['name_he'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='שם פרטי')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='שם משפחה')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('max_weekly_hours', models.PositiveSmallIntegerField(default=40, verbose_name='שעות שבועיות מקסימום')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school')),
            ],
            options={
                'verbose_name': 'מורה',
                'verbose_name_plural': 'מורים',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='שעות הוראה')),
                ('bagrut_bonus_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='שעות גמול בגרות')),
                ('bagrut_exam_code', models.CharField(blank=True, max_length=20, verbose_name='סמל שאלון בגרות')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='school.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subjects.teacher')),
            ],
            options={
                'verbose_name': 'שיבוץ הוראה',
                'verbose_name_plural': 'שיבוצי הוראה',
            },
        ),
    ]
