# Generated by Django 6.0.4 on 2026-05-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolclass_homeroom_teacher_and_more'),
        ('subjects', '0002_teacher_day_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=200, verbose_name='שם התפקיד')),
                ('context', models.CharField(blank=True, default='', max_length=40, verbose_name='הקשר')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='תיאור')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='שעות שבועיות')),
                ('stipend_fraction', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='גמול תפקיד')),
                ('must_teach_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='חובת הוראה')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='הערות')),
            ],
            options={
                'verbose_name': 'תפקיד מורה',
                'verbose_name_plural': 'תפקידי מורים',
                'ordering': ['role_title'],
            },
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='מזהה קבוצה'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='שורת מקור'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='source_sheet',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='גיליון מקור'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='student_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='מספר תלמידים בקבוצה'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='track_label',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='תווית מסלול'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='bagrut_exam_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='סמל שאלון בגרות'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='subjects.teacher', verbose_name='מורה'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name_he'), name='subject_school_name_unique'),
        ),
        migrations.AddField(
            model_name='teacherrole',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_roles', to='school.school'),
        ),
        migrations.AddField(
            model_name='teacherrole',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='subjects.teacher', verbose_name='מורה'),
        ),
    ]
