# Generated by Django 6.0.4 on 2026-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolclass_homeroom_teacher_and_more'),
        ('subjects', '0003_teacherrole_teachingassignment_group_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='additional_classes',
            field=models.ManyToManyField(blank=True, related_name='pooled_assignments', to='school.schoolclass', verbose_name='כיתות נוספות בקבוצה'),
        ),
    ]
