# Generated by Django 6.0.4 on 2026-05-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolclass_homeroom_teacher_and_more'),
        ('subjects', '0004_teachingassignment_additional_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='שם תגית')),
                ('color', models.CharField(default='#6366F1', max_length=7, verbose_name='צבע')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tags', to='school.school')),
            ],
            options={
                'verbose_name': 'תגית מורים',
                'verbose_name_plural': 'תגיות מורים',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subjects.teachertag', verbose_name='תגיות'),
        ),
        migrations.AddConstraint(
            model_name='teachertag',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='teacher_tag_school_name_unique'),
        ),
    ]
