# Generated by Django 6.0.4 on 2026-06-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_teachertag_teacher_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertag',
            name='kind',
            field=models.CharField(choices=[('department', 'מחלקה'), ('coordinator', 'ריכוז'), ('custom', 'מותאם אישית')], default='custom', max_length=20, verbose_name='סוג תגית'),
        ),
        migrations.AddField(
            model_name='teachertag',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_tags', to='subjects.subject', verbose_name='מקצוע'),
        ),
    ]
