# Generated by Django 6.0.4 on 2026-04-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('constraint_type', models.CharField(choices=[('teacher_availability', 'זמינות מורה'), ('max_daily_hours_class', 'מקסימום שעות יומי לכיתה'), ('max_daily_hours_teacher', 'מקסימום שעות יומי למורה'), ('subject_spread', 'פיזור מקצוע לאורך השבוע'), ('consecutive_hours', 'שיעורים צמודים'), ('preferred_periods', 'שיעורים מועדפים'), ('no_last_period', 'לא בשיעור אחרון'), ('custom', 'מותאם אישית')], max_length=30, verbose_name='סוג אילוץ')),
                ('priority', models.CharField(choices=[('hard', 'חובה'), ('soft', 'העדפה')], default='hard', max_length=4, verbose_name='עדיפות')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('parameters', models.JSONField(default=dict, verbose_name='פרמטרים')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='school.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='school.schoolclass', verbose_name='כיתה')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='subjects.subject', verbose_name='מקצוע')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='subjects.teacher', verbose_name='מורה')),
            ],
            options={
                'verbose_name': 'אילוץ',
                'verbose_name_plural': 'אילוצים',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם')),
                ('academic_year', models.CharField(max_length=9, verbose_name='שנת לימודים')),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('generating', 'בתהליך יצירה'), ('completed', 'הושלם'), ('failed', 'נכשל'), ('published', 'פורסם')], default='draft', max_length=10, verbose_name='סטטוס')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('solver_log', models.TextField(blank=True, verbose_name='לוג פתרון')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.school')),
            ],
            options={
                'verbose_name': 'מערכת שעות',
                'verbose_name_plural': 'מערכות שעות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='school.room')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='school.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='subjects.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='school.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timetable')),
            ],
            options={
                'verbose_name': 'שיעור במערכת',
                'verbose_name_plural': 'שיעורים במערכת',
                'unique_together': {('timetable', 'school_class', 'time_slot')},
            },
        ),
    ]
