# Generated by Django 6.0.4 on 2026-05-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('school', '0002_schoolclass_homeroom_teacher_and_more'),
        ('subjects', '0004_teachingassignment_additional_classes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timetable', 'school_class', 'time_slot', 'teacher')},
        ),
    ]
