# Generated by Django 6.0.4 on 2026-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_constraint_constraint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='נעול'),
        ),
    ]
