# Generated by Django 6.0.4 on 2026-05-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_timetableentry_locked'),
        ('subjects', '0005_teachertag_teacher_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='subjects.teachertag', verbose_name='תגית מורים'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('teacher_availability', 'זמינות מורה'), ('max_daily_hours_class', 'מקסימום שעות יומי לכיתה'), ('max_daily_hours_teacher', 'מקסימום שעות יומי למורה'), ('subject_spread', 'פיזור מקצוע לאורך השבוע'), ('consecutive_hours', 'שיעורים צמודים'), ('consecutive_pair', 'זוג שיעורים רצופים'), ('lunch_break', 'הפסקת אוכל'), ('preferred_periods', 'שיעורים מועדפים'), ('no_last_period', 'לא בשיעור אחרון'), ('group_blocked_slot', 'חסימת קבוצת מורים בשיעור'), ('custom', 'מותאם אישית')], max_length=30, verbose_name='סוג אילוץ'),
        ),
    ]
