# Generated by Django 6.0.4 on 2026-05-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_constraint_tag_alter_constraint_constraint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='progress',
            field=models.JSONField(blank=True, default=dict, verbose_name='התקדמות'),
        ),
    ]
