# Generated by Django 6.0.4 on 2026-06-02 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_timetable_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('triggered_by', models.CharField(choices=[('ai_move', 'הזזת שיעור על־ידי AI'), ('ai_swap', 'החלפת שיעורים על־ידי AI'), ('manual_move', 'הזזה ידנית'), ('manual_swap', 'החלפה ידנית'), ('manual_save', 'שמירה ידנית'), ('before_restore', 'לפני שחזור'), ('before_build', 'לפני בנייה אוטומטית')], max_length=20, verbose_name='מקור')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='תיאור')),
                ('entries_data', models.JSONField(default=list, verbose_name='נתוני שיעורים')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ביצע/ה')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scheduling.timetable')),
            ],
            options={
                'verbose_name': 'גרסת מערכת',
                'verbose_name_plural': 'גרסאות מערכת',
                'ordering': ['-created_at'],
            },
        ),
    ]
