# Generated by Django 6.0.4 on 2026-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_timetablesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='constraint_type',
            field=models.CharField(choices=[('teacher_availability', 'זמינות מורה'), ('max_daily_hours_class', 'מקסימום שעות יומי לכיתה'), ('max_daily_hours_teacher', 'מקסימום שעות יומי למורה'), ('subject_spread', 'פיזור מקצוע לאורך השבוע'), ('consecutive_hours', 'שיעורים צמודים'), ('consecutive_pair', 'זוג שיעורים רצופים'), ('lunch_break', 'הפסקת אוכל'), ('preferred_periods', 'שיעורים מועדפים'), ('no_last_period', 'לא בשיעור אחרון'), ('group_blocked_slot', 'חסימת קבוצת מורים בשיעור'), ('subject_day_blackout', 'חסימת מקצוע ביום'), ('custom', 'מותאם אישית')], max_length=30, verbose_name='סוג אילוץ'),
        ),
    ]
